# Generated by Django 4.2.5 on 2023-10-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('gdp_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gdp_growth', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
