# Generated by Django 4.2.5 on 2023-10-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JsonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='gdp_value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
